/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00000: line 1: 14801 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 0 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00001: line 1: 14817 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 1 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00002: line 1: 14829 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 2 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00003: line 1: 14840 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 3 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00004: line 1: 14851 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 4 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00005: line 1: 14862 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 5 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00006: line 1: 14873 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 6 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00007: line 1: 14884 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 7 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00008: line 1: 14895 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 8 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00009: line 1: 14906 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 9 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00010: line 1: 14917 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 10 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00011: line 1: 14928 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 11 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00012: line 1: 14942 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 12 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00013: line 1: 14954 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 13 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00014: line 1: 14970 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 14 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00015: line 1: 14985 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 15 16
/home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/run/config.00016: line 1: 15000 Segmentation fault      (core dumped) /g/data/v45/jm5970/env/track_env/bin/python /home/156/jm5970/github/phd_source/trackeddy_utils/chelton2py/Chelton2npy.py 16 16
